import {useEffect, useRef} from "react";
import {categoryStacks} from "../features/items/item-search-reducer.js";

export default function FiltersDialog({categories, constants, filters, onClose, onReset, onToggle, onValue, open, triggerRef}) {
    const dialogRef = useRef(null);
    useEffect(function() {
        if (!open) return undefined;
        const bodyHadModalOpen = document.body.classList.contains("modal-open"); document.body.classList.add("modal-open");
        const inert = new Map(); let child = dialogRef.current;
        while (child?.parentElement) { const parent = child.parentElement; for (const sibling of parent.children) if (sibling !== child && !inert.has(sibling)) { inert.set(sibling, sibling.getAttribute("inert")); sibling.setAttribute("inert", ""); } if (parent === document.body) break; child = parent; }
        function keydown(event) { if (event.key === "Escape") { event.preventDefault(); onClose(); return; } if (event.key !== "Tab") return; const all = Array.from(dialogRef.current?.querySelectorAll("a[href], button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex='-1'])") || []).filter(element => !element.hidden); if (!all.length) return; const first = all[0], last = all.at(-1); if (event.shiftKey && (document.activeElement === first || !dialogRef.current.contains(document.activeElement))) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && (document.activeElement === last || !dialogRef.current.contains(document.activeElement))) { event.preventDefault(); first.focus(); } }
        window.addEventListener("keydown", keydown); dialogRef.current?.focus();
        return function() { window.removeEventListener("keydown", keydown); for (const [element, previous] of inert) { if (previous == null) element.removeAttribute("inert"); else element.setAttribute("inert", previous); } if (!bodyHadModalOpen) document.body.classList.remove("modal-open"); setTimeout(() => triggerRef.current?.focus()); };
    }, [open, onClose, triggerRef]);
    if (!open) return null;
    return <div ref={dialogRef} id="filtersModal" className="modal d-block show" tabIndex="-1" role="dialog" aria-modal="true" aria-labelledby="filtersModalLabel"><div className="modal-dialog modal-xl" role="document"><div className="modal-content"><div className="modal-header"><h2 className="modal-title h5" id="filtersModalLabel">Select search filters</h2><button type="button" className="close" aria-label="Close" onClick={onClose}><span aria-hidden="true">&times;</span></button></div><div className="modal-body"><div className="filters-picker-toolbar"><p className="filters-picker-toolbar-copy text-body">Select filters to narrow item search results. Search again to apply changes.</p><button type="button" className="filters-picker-reset btn btn-primary btn-sm" onClick={onReset}>Reset to defaults</button></div><div className="filters-picker-grid">{categoryStacks(categories).map((stack, index) => <div className="filters-picker-stack" key={index}>{stack.map(category => <section className="filters-picker-category list-group-item" key={category.name}><h6 className="filters-picker-category-title">{category.name}</h6><div className="list-group list-group-flush">{category.getItemStatInfo.map(stat => stat.type !== "select" ? <button key={stat.var} type="button" aria-pressed={Object.hasOwn(filters, stat.var)} className="filters-picker-option list-group-item list-group-item-action list-group-item-light" onClick={() => onToggle(stat.var)}><span className="d-flex align-items-center justify-content-between"><span>{stat.display}</span><i className={`fas ml-2 ${Object.hasOwn(filters, stat.var) ? "text-success fa-check" : "text-danger fa-times"}`} aria-hidden="true" /></span></button> : <select key={stat.var} aria-label={stat.display} value={filters[stat.var]?.[0] || ""} className="filters-picker-option list-group-item list-group-item-action list-group-item-light" style={stat.var === "alignRestriction" ? {whiteSpace: "pre"} : undefined} onChange={event => onValue(stat.var, event.target.value)}><option value="">Choose a {stat.display}...</option>{(constants.selectShortOptions[stat.var] || []).map((option, value) => <option key={value} value={value} className={stat.var === "alignRestriction" ? "text-monospace" : undefined}>{stat.var === "alignRestriction" ? option.replace(/\s/g, " ") : option}</option>)}</select>)}</div></section>)}</div>)}</div></div></div></div></div>;
}
