import {BuilderModal} from "./ImportExportDialog.jsx";

export default function BuilderListsDialog({dialog, state, onClose, onSubmit}) {
    const title = dialog === "clear" ? "Are you sure?" : dialog === "delete-character" || dialog === "delete-variant" ? "Are you sure?" : dialog === "add-character" ? "Add Character" : dialog === "add-variant" ? "Add Variant" : dialog === "edit-character" ? "Edit Character" : "Edit Variant";
    const confirmation = dialog === "clear" ? `Are you sure you want to clear all of ${state.selectedList.name}'s items? Only locked items will remain.` : dialog === "delete-character" ? `Are you sure you want to delete ${state.allLists[state.selectedListIndex].name}?` : dialog === "delete-variant" ? "Are you sure you want to delete the current list variant?" : null;
    if (confirmation) return <BuilderModal label={title} onClose={onClose}><div className="modal-body"><p>{confirmation}</p><button className="btn btn-primary" type="button" onClick={onSubmit}>Yes</button></div></BuilderModal>;
    const name = state.dialogName || (dialog === "edit-character" ? state.allLists[state.selectedListIndex].name : dialog === "edit-variant" ? state.selectedList.name : "");
    const errorId = "builder-list-name-error";
    return <BuilderModal label={title} onClose={onClose} initialFocus="#builder-list-name"><form className="modal-body" noValidate onSubmit={event => { event.preventDefault(); onSubmit(name); }}><label htmlFor="builder-list-name">Name</label><input id="builder-list-name" className="form-control" pattern="[A-Za-z\\s\\d]+" value={name} aria-invalid={Boolean(state.dialogError)} aria-describedby={state.dialogError ? errorId : undefined} onChange={event => onSubmit(event.target.value, true)} />{state.dialogError && <p id={errorId} role="alert" className="text-danger mb-0">{state.dialogError}</p>}<button className="btn btn-primary mt-3" type="submit">{dialog === "add-character" || dialog === "add-variant" ? "Add" : "Save"}</button></form></BuilderModal>;
}
