export default function CharacterPanel({state, onAction, onDialog}) {
    const selectedCharacter = state.allLists[state.selectedListIndex];
    return <section className="col-lg-6 col-12 mb-4"><div className="card border-primary"><div className="card-header py-2"><div className="row align-items-center justify-content-between"><h1 className="col-auto h4 mb-0" id="builder-character-heading">Character</h1><span className="col-auto h6 mb-0">{state.clientSideDataSize || ""}</span></div></div><div className="card-body p-3">
        <div className="input-group mb-3"><select aria-label="Character" className="custom-select" value={String(state.selectedListIndex)} onChange={event => onAction({type: "variant/select", listIndex: Number(event.target.value), variantIndex: 0})}>{state.allLists.map((list, index) => <option key={list.name} value={index}>{list.name}</option>)}</select><div className="input-group-append"><button className="btn btn-outline-danger" type="button" aria-label="Delete Character" onClick={() => onDialog("delete-character")}>Delete</button><button className="btn btn-outline-secondary" type="button" aria-label="Edit Character" onClick={() => onDialog("edit-character")}>Edit</button><button className="btn btn-outline-success" type="button" aria-label="Add Character" onClick={() => onDialog("add-character")}>Add</button></div></div>
        <div className="input-group"><select aria-label="Variant" className="custom-select" value={String(state.selectedListVariantIndex)} onChange={event => onAction({type: "variant/select", listIndex: state.selectedListIndex, variantIndex: Number(event.target.value)})}>{(selectedCharacter?.variants || []).map((variant, index) => <option key={`${variant.name}-${index}`} value={index}>{variant.name} Variant</option>)}</select><div className="input-group-append"><button className="btn btn-outline-danger" type="button" aria-label="Delete Variant" onClick={() => onDialog("delete-variant")}>Delete</button><button className="btn btn-outline-secondary" type="button" aria-label="Edit Variant" onClick={() => onDialog("edit-variant")}>Edit</button><button className="btn btn-outline-success" type="button" aria-label="Add Variant" onClick={() => onAction({type: "variant/add", listIndex: state.selectedListIndex, variant: {...state.selectedList, name: `${state.selectedList.name} Copy`}})}>Add</button></div></div>
        {state.selectedListVariantIndex > 0 && <button className="btn btn-block btn-outline-primary mt-1" type="button" onClick={() => onAction({type: "variant/make-primary"})}>Set Variant as Primary</button>}
        <div className="btn-group d-flex mt-4" role="group" aria-label="Character Options"><button type="button" className="btn btn-outline-secondary col" onClick={() => onDialog("import")}>Import</button><button type="button" className="btn btn-outline-secondary col" onClick={() => onDialog("export")}>Export</button><button type="button" className="btn btn-outline-secondary col" onClick={() => onDialog("columns")}>Hide/Show Columns</button><button type="button" className="btn btn-outline-danger col" onClick={() => onDialog("clear")}>Clear Items</button></div>
    </div></div></section>;
}
