function CharacterOptions({className, columnsOpen, columnsTriggerRef, onDialog}) {
    return <div className={className} role="group" aria-label="Character Options"><button type="button" className="btn btn-outline-secondary col" onClick={() => onDialog("import")}>Import</button><button type="button" className="btn btn-outline-secondary col" onClick={() => onDialog("export")}>Export</button><button type="button" className="btn btn-outline-secondary col" aria-haspopup="dialog" aria-expanded={columnsOpen} onClick={event => { columnsTriggerRef.current = event.currentTarget; onDialog("columns"); }}>Hide/Show Columns</button><button type="button" className="btn btn-outline-danger col" onClick={() => onDialog("clear")}>Clear Items</button></div>;
}

export default function CharacterPanel({state, columnsOpen, columnsTriggerRef, storageStatus, onAction, onDialog}) {
    const selectedCharacter = state.allLists[state.selectedListIndex];
    return <section className="col-lg-6 col-12 mb-4"><div className="card border-primary"><div className="card-header py-2"><div className="row align-items-center justify-content-between"><h1 className="col-auto h4 mb-0" id="builder-character-heading">Character</h1><div className="col-auto d-flex flex-wrap align-items-center justify-content-end"><span className="h6 mb-0 mr-2">{state.clientSideDataSize || ""}</span>{storageStatus}</div></div></div><div className="card-body p-3">
        <div className="input-group mb-3"><select aria-label="Character" className="custom-select" value={String(state.selectedListIndex)} onChange={event => onAction({type: "variant/select", listIndex: Number(event.target.value), variantIndex: 0})}>{state.allLists.map((list, index) => <option key={list.name} value={index}>{list.name}</option>)}</select><div className="input-group-append"><button className="btn btn-outline-danger" type="button" aria-label="Delete Character" onClick={() => onDialog("delete-character")}><i className="fas fa-trash" aria-hidden="true" /></button><button className="btn btn-outline-secondary" type="button" aria-label="Edit Character" onClick={() => onDialog("edit-character")}><i className="fas fa-edit" aria-hidden="true" /></button><button className="btn btn-outline-success" type="button" aria-label="Add Character" onClick={() => onDialog("add-character")}><i className="fas fa-plus" aria-hidden="true" /></button></div></div>
        <div className="input-group"><select aria-label="Variant" className="custom-select" value={String(state.selectedListVariantIndex)} onChange={event => onAction({type: "variant/select", listIndex: state.selectedListIndex, variantIndex: Number(event.target.value)})}>{(selectedCharacter?.variants || []).map((variant, index) => <option key={`${variant.name}-${index}`} value={index}>{variant.name} Variant</option>)}</select><div className="input-group-append"><button className="btn btn-outline-danger" type="button" aria-label="Delete Variant" onClick={() => onDialog("delete-variant")}><i className="fas fa-trash" aria-hidden="true" /></button><button className="btn btn-outline-secondary" type="button" aria-label="Edit Variant" onClick={() => onDialog("edit-variant")}><i className="fas fa-edit" aria-hidden="true" /></button><button className="btn btn-outline-success" type="button" aria-label="Add Variant" onClick={() => onDialog("add-variant")}><i className="fas fa-clone" aria-hidden="true" /></button></div></div>
        {state.selectedListVariantIndex > 0 && <button className="btn btn-block btn-outline-primary mt-1" type="button" onClick={() => onAction({type: "variant/make-primary"})}>Set Variant as Primary</button>}
        <div className="row mt-4"><CharacterOptions className="btn-group d-none d-md-flex col" columnsOpen={columnsOpen} columnsTriggerRef={columnsTriggerRef} onDialog={onDialog} /><CharacterOptions className="btn-group-vertical d-flex d-md-none col" columnsOpen={columnsOpen} columnsTriggerRef={columnsTriggerRef} onDialog={onDialog} /></div>
    </div></div></section>;
}
