import {CHARM_OPTIONS, RUNE_CHARM_ID} from "./item-constants.js";
import {getItemRestrictionText} from "./builder-derivations.js";
import {BuilderModal} from "./ImportExportDialog.jsx";

function visibleStats(state) {
    return state.statInfo.filter(stat => stat.showColumn && stat.var !== "name" && stat.var !== "slot");
}

export default function EquipmentPanel({state, totals, restrictions, onAction, onOpen, onPick, onClose}) {
    const stats = visibleStats(state);
    const current = state.currentItem;
    const choices = current ? (state.itemsBySlot[current.slot] || []).filter(item => !state.searchString || item.name.toLowerCase().includes(state.searchString.toLowerCase())) : [];
    return <section className="row"><div className="table-responsive"><table className="table table-striped table-hover table-sm table-bordered"><thead className="thead-dark"><tr><th>Slot</th><th>Lock</th><th>Name</th>{stats.map(stat => <th key={stat.var} title={stat.display}>{stat.short}</th>)}</tr></thead><tbody><tr><td /><td><button type="button" className="btn btn-link p-0" aria-label="Toggle all item locks" onClick={() => onAction({type: "items/toggle-lock"})}>Lock</button></td><td>Total</td>{stats.map(stat => <td key={stat.var}>{totals[stat.var] ?? ""}</td>)}</tr>{state.selectedList.items.map((item, index) => <tr key={index}><td className={restrictions[index]?.length ? "border border-danger" : ""} title={getItemRestrictionText(restrictions[index], item)}>{item.slot}</td><td><button type="button" className="btn btn-link p-0" aria-label={`Toggle lock for slot ${index + 1}`} onClick={() => onAction({type: "item/toggle-lock", index})}>{item.locked ? "Locked" : "Unlocked"}</button></td><th scope="row"><button type="button" className="btn btn-link p-0" onClick={() => onOpen(index)}>{item.name || "-"}</button></th>{stats.map(stat => <td key={stat.var}>{item[stat.var] ?? ""}</td>)}</tr>)}</tbody></table></div>{current && <BuilderModal label="Choose Item" onClose={onClose}><div className="modal-body"><label htmlFor="itemChoiceSearch">Search items</label><input id="itemChoiceSearch" className="form-control" value={state.searchString} onChange={event => onAction({type: "search/text", value: event.target.value})} />{(current.slot === 13 || current.slot === 2) && <button type="button" className="btn btn-primary mt-3" onClick={() => onAction({type: "rune/toggle-mode"})}>{state.isRuneCrafting ? "Items" : "Runecraft Customizer"}</button>}{state.isRuneCrafting ? <div className="mt-3">{state.charmSelectors.map((selection, index) => <select className="custom-select mb-2" aria-label={`Rune charm ${index + 1}`} value={selection} key={index} onChange={event => { const charmSelectors = state.charmSelectors.slice(); charmSelectors[index] = event.target.value; onAction({type: "ui/patch", value: {charmSelectors}}); }}><option value="A">--Select--</option>{Object.values(CHARM_OPTIONS).map(option => <option key={option.id} value={option.id}>{option.label}</option>)}</select>)}<button type="button" className="btn btn-primary" onClick={() => onPick({id: RUNE_CHARM_ID, slot: current.slot, name: "Runecharm"}, true)}>Save Runecharm</button></div> : <table className="table table-sm mt-3"><thead><tr><th>Name</th>{stats.map(stat => <th key={stat.var}>{stat.short}</th>)}</tr></thead><tbody>{choices.map(item => <tr key={item.id}><td><button className="btn btn-link p-0" type="button" disabled={current.locked} onClick={() => onPick(item)}>{item.name}</button></td>{stats.map(stat => <td key={stat.var}>{item[stat.var] ?? ""}</td>)}</tr>)}</tbody></table>}</div></BuilderModal>}</section>;
}
