import {ATTRIBUTE_NAMES, AMULET_OPTIONS, HAZELNUT_OPTIONS, LONGHOUSE_OPTIONS} from "./item-constants.js";

export default function QuestModifiersPanel({collapsed, onCollapsed, selectedList, onStat}) {
    const base = selectedList.baseStats;
    const ksm = selectedList.ksmStats;
    const baseTotal = ATTRIBUTE_NAMES.reduce((total, stat) => total + Number(base[stat] || 0), 0);
    const ksmTotal = ATTRIBUTE_NAMES.reduce((total, stat) => total + Number(ksm[stat] || 0), 0);
    const canSelectQuest = baseTotal < 244;
    return <div className="border-top mt-3 pt-2"><h2 className="h5 mb-0"><button className={`btn btn-link btn-block h5 text-left px-0 py-1 collapse-toggle${collapsed ? " collapsed" : ""}`} type="button" aria-expanded={String(!collapsed)} aria-controls="ksmQuestMods" onClick={onCollapsed}><i className="fas fa-chevron-right mr-2 collapse-caret" aria-hidden="true" />KSM Swap/Quest Mods</button></h2>{!collapsed && <div id="ksmQuestMods"><div className="row mb-3">{ATTRIBUTE_NAMES.map(stat => <div className="col-4 col-sm-2 text-center" key={stat}><label className="col-form-label col-form-label-sm" htmlFor={`ksm-${stat}`}>{stat.slice(0, 3)}</label><input type="number" id={`ksm-${stat}`} className="form-control form-control-sm" value={ksm[stat]} onChange={event => onStat("ksmStats", stat, Number(event.target.value))} /></div>)}</div>{ksmTotal !== 0 && <p className="text-danger">Total KSM stats must equal zero.</p>}{ksmTotal === 0 && ATTRIBUTE_NAMES.reduce((total, stat) => total + Math.abs(Number(ksm[stat] || 0)), 0) > 6 && <p className="text-danger">You can only swap stats a maximum of three times.</p>}<div className="row">{[["longhouse", "Longhouse", LONGHOUSE_OPTIONS], ["amulet", "Amulet", AMULET_OPTIONS], ["hazelnut", "Hazelnut", HAZELNUT_OPTIONS]].map(([field, label, options]) => <div className="input-group input-group-sm col-8 col-sm-4 mb-3" key={field}><div className="input-group-prepend"><label className="input-group-text" htmlFor={`${field}Select`}>{label}</label></div><select className="custom-select custom-select-sm" id={`${field}Select`} disabled={!canSelectQuest} value={base[field]} onChange={event => onStat("baseStats", field, Number(event.target.value))}><option value="-1">-</option>{options.map((option, index) => <option key={option} value={index}>{option}</option>)}</select></div>)}</div><div className="row">{[["quest_hp", "Quest HP"], ["quest_mana", "Quest Mana"], ["quest_move", "Quest Mv"]].map(([field, label]) => <div className="input-group input-group-sm col-8 col-sm-4 mb-3" key={field}><div className="input-group-prepend"><label className="input-group-text" htmlFor={field}>{label}</label></div><input type="number" min="0" max="238327" id={field} className="form-control form-control-sm" value={base[field]} onChange={event => onStat("baseStats", field, Number(event.target.value))} /></div>)}</div></div>}</div>;
}
